const qs=s=>document.querySelector(s);
const menu=qs('.menu'),nav=qs('nav');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}));
const dialog=qs('#gallery-dialog');let slides=[],slideIndex=0,lastTrigger=null;
function renderSlide(){const area=qs('#gallery-media');area.replaceChildren();const src=slides[slideIndex],video=/\.(webm|mp4)$/.test(src),el=document.createElement(video?'video':'img');el.src=src;if(video){el.controls=true;el.playsInline=true}else el.alt=qs('#gallery-title').textContent+' view '+(slideIndex+1);area.append(el);qs('#gallery-count').textContent=(slideIndex+1)+' / '+slides.length;qs('#gallery-prev').disabled=slides.length<2;qs('#gallery-next').disabled=slides.length<2}
function openGallery(title,urls,trigger,original){if(!urls.length)return;lastTrigger=trigger;slides=urls;slideIndex=0;qs('#gallery-title').textContent=title;qs('#gallery-original').hidden=!original;if(original)qs('#gallery-original').href=original;renderSlide();dialog.showModal()}
qs('#gallery-close').addEventListener('click',()=>dialog.close());
function moveSlide(n){slideIndex=(slideIndex+n+slides.length)%slides.length;renderSlide()}
qs('#gallery-prev').addEventListener('click',()=>moveSlide(-1));qs('#gallery-next').addEventListener('click',()=>moveSlide(1));
dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')moveSlide(-1);if(e.key==='ArrowRight')moveSlide(1)});
dialog.addEventListener('close',()=>{qs('#gallery-media').replaceChildren();lastTrigger?.focus()});
dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close()});
let projects=[],activeProject=0,activeMedia=0,projectCategory='All projects';
const categoryLabels={'AI & Computer Vision':'AI & vision','Data Analytics':'Data analytics','Machine Learning':'Machine learning','Intelligent Applications':'Intelligent apps','Web Development':'Web & games'};
function newButton(label,className,handler){const b=document.createElement('button');b.type='button';b.className=className;b.textContent=label;b.addEventListener('click',handler);return b}
function addLink(container,label,url,className='studio-action'){if(!url)return;const a=document.createElement('a');a.textContent=label;a.href=url;a.className=className;if(url.startsWith('http')){a.target='_blank';a.rel='noopener noreferrer'}container.append(a)}
function renderDirectory(){const directory=qs('.project-directory');directory.replaceChildren();let count=0;projects.forEach((p,i)=>{if(projectCategory!=='All projects'&&p.category!==projectCategory)return;count++;const b=newButton('','project-choice',()=>{activeProject=i;activeMedia=0;renderDirectory();renderStage()});b.classList.toggle('selected',i===activeProject);b.setAttribute('aria-pressed',String(i===activeProject));const index=document.createElement('span');index.className='choice-number';index.textContent=String(i+1).padStart(2,'0');const title=document.createElement('span');title.textContent=p.title;b.append(index,title);directory.append(b)});qs('#project-status').textContent=count+' projects in this category';document.querySelectorAll('.studio-filters button').forEach(b=>{const selected=b.dataset.category===projectCategory;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))})}
function renderPreview(){const p=projects[activeProject],preview=qs('#stage-preview');preview.replaceChildren();preview.disabled=!p.media.length;preview.className=p.title==='Alpha'?'portrait-stage':'';preview.setAttribute('aria-label',p.media.length?'Expand '+p.title+' screenshot':'');if(p.media.length){const src=p.media[activeMedia],video=/\.(mp4|webm)$/.test(src),el=document.createElement(video?'video':'img');el.src=src;if(video){el.muted=true;el.playsInline=true;el.preload='none';el.poster='assets/projects/Pathfinderai/poster.jpg'}else el.alt=p.title+' — actual project screen';preview.append(el);const tag=document.createElement('span');tag.className='expand-tag';tag.textContent=video?'Watch project recording':'Expand screenshot';preview.append(tag)}else{const cover=document.createElement('div');cover.className='typographic-stage '+(p.title==='Life at Home'?'game-type':'');const label=document.createElement('span');label.textContent=p.title==='Life at Home'?'THE PLAYABLE PROJECT':'THE CHATBOT PROJECT';const title=document.createElement('strong');title.textContent=p.title==='Life at Home'?'Life at Home.':'TechBuddy.';const caption=document.createElement('span');caption.textContent=p.title==='Life at Home'?'Explore. Interact. Play.':'Hardware guidance through conversation.';cover.append(label,title,caption);preview.append(cover)}
document.querySelectorAll('#stage-thumbnails button').forEach((b,i)=>{b.classList.toggle('selected',i===activeMedia);b.setAttribute('aria-pressed',String(i===activeMedia))})}
function renderStage(){const p=projects[activeProject];qs('#stage-kind').textContent=p.category;qs('#stage-number').textContent=String(activeProject+1).padStart(2,'0')+' / '+String(projects.length).padStart(2,'0');qs('#stage-title').textContent=p.title;qs('#stage-description').textContent=p.description;qs('#stage-tech').textContent=p.tech;const thumbs=qs('#stage-thumbnails');thumbs.replaceChildren();p.media.slice(0,6).forEach((src,i)=>{const b=newButton('','stage-thumb',()=>{activeMedia=i;renderPreview()});b.setAttribute('aria-label','Show '+p.title+' view '+(i+1));if(/\.(webm|mp4)$/.test(src)){const im=document.createElement('img');im.src='assets/projects/Pathfinderai/poster.jpg';im.alt='Recording preview';b.append(im)}else{const im=document.createElement('img');im.src=src;im.alt='View '+(i+1);im.loading='lazy';b.append(im)}thumbs.append(b)});const actions=qs('#stage-actions');actions.replaceChildren();if(p.media.length)actions.append(newButton('View all '+p.media.length+' '+(p.media.length===1?'view':'views'),'studio-action',e=>openGallery(p.title,p.media,e.currentTarget)));addLink(actions,p.demoLabel,p.demo,'studio-action primary');addLink(actions,'GitHub repository',p.repo,'studio-repo');renderPreview()}
qs('#stage-preview').addEventListener('click',e=>{const p=projects[activeProject];openGallery(p.title,p.media,e.currentTarget);slideIndex=activeMedia;renderSlide()});
fetch('assets/projects.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{projects=d;const cats=['All projects',...new Set(projects.map(p=>p.category))];cats.forEach(c=>{const b=newButton(categoryLabels[c]||c,'studio-filter',()=>{projectCategory=c;activeProject=projects.findIndex(p=>c==='All projects'||p.category===c);activeMedia=0;renderDirectory();renderStage()});b.dataset.category=c;qs('.studio-filters').append(b)});renderDirectory();renderStage()}).catch(()=>{qs('#stage-description').textContent='Projects could not load. Refresh the page to retry.'});
let certificates=[],certCategory='All documents';
function renderCertificates(){const wall=qs('.certificate-wall');wall.replaceChildren();const visible=certificates.filter(c=>certCategory==='All documents'||c.category===certCategory);qs('.cert-result-count').textContent=visible.length+' of '+certificates.length+' documents';qs('#cert-total').textContent=certificates.length;visible.forEach(c=>{const index=certificates.indexOf(c),a=document.createElement('a');a.className='archive-certificate';a.href=c.original;a.target='_blank';a.rel='noopener noreferrer';a.addEventListener('click',e=>{e.preventDefault();openGallery(c.title,[c.preview],a,c.original)});const photo=document.createElement('div');photo.className='archive-photo';const im=document.createElement('img');im.src=c.preview;im.alt=c.title+' — original document';im.loading='lazy';photo.append(im);const metadata=document.createElement('div');metadata.className='archive-meta';const category=document.createElement('span');category.className='archive-category';category.textContent=c.category+' / '+String(index+1).padStart(2,'0');const h=document.createElement('h3');h.textContent=c.title;const issuer=document.createElement('p');issuer.textContent=c.issuer;const date=document.createElement('small');date.textContent=c.date;const view=document.createElement('span');view.className='archive-open';view.textContent='Take a closer look';metadata.append(category,h,issuer,date,view);a.append(photo,metadata);wall.append(a)});document.querySelectorAll('.certificate-filters button').forEach(b=>{const sel=b.dataset.category===certCategory;b.classList.toggle('selected',sel);b.setAttribute('aria-pressed',String(sel))})}
fetch('assets/certificates.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{certificates=d;['All documents',...new Set(d.map(c=>c.category))].forEach(c=>{const b=newButton(c,'archive-filter',()=>{certCategory=c;renderCertificates()});b.dataset.category=c;qs('.certificate-filters').append(b)});renderCertificates()}).catch(()=>{qs('.cert-result-count').textContent='Documents could not load. Refresh to retry.'});
