const $=s=>document.querySelector(s);let data=[],selected=[];
const metrics=[
['Life expectancy at birth, total (years)','Life expectancy','years'],
['Immunization, DPT (% of children ages 12-23 months)','DPT immunization','%'],
['Mortality rate, under-5 (per 1,000)','Under-five mortality','per 1,000'],
['Current health expenditure (% of GDP)','Health expenditure','% of GDP'],
['Current health expenditure per capita (current US$)','Health spending per capita','US$'],
['People using at least basic sanitation services (% of population)','Basic sanitation','%'],
['People using at least basic drinking water services (% of population)','Basic drinking water','%'],
['Public spending on education, total (% of GDP)','Education expenditure','% of GDP'],
['Domestic general government health expenditure (% of GDP)','Government health expenditure','% of GDP']];
metrics.forEach((m,i)=>$('#metric').add(new Option(m[1],i)));
function format(v){return v==null?'Unavailable':new Intl.NumberFormat('en',{maximumFractionDigits:2}).format(v)}
function update(){const [key,label,unit]=metrics[$('#metric').value],year=Number($('#year').value),country=$('#country').value;selected=data.filter(r=>r.Year===year).sort((a,b)=>(b[key]??-Infinity)-(a[key]??-Infinity));const valid=selected.filter(r=>r[key]!=null),max=Math.max(...valid.map(r=>r[key]),1);$('#average').textContent=format(valid.length?valid.reduce((s,r)=>s+r[key],0)/valid.length:null)+' '+unit;$('#focus-label').textContent=country+' · '+year;$('#focus-value').textContent=format(selected.find(r=>r['Country Name']===country)?.[key])+' '+unit;$('#coverage').textContent=valid.length+' / 12';$('#chart-title').textContent=label+' · '+year;$('#trend-title').textContent=country+' over time';$('#unit-note').textContent='Indicator: '+label+' ('+unit+')';$('#bars').replaceChildren();selected.forEach(r=>{const row=document.createElement('div');row.className='row';const name=document.createElement('span');name.textContent=r['Country Name'];const track=document.createElement('div');track.className='track';const bar=document.createElement('div');bar.className='bar';bar.style.width=(r[key]==null?0:r[key]/max*100)+'%';if(r['Country Name']===country)bar.style.background='#ef6a7e';track.append(bar);const v=document.createElement('span');v.className='value';v.textContent=format(r[key]);row.append(name,track,v);$('#bars').append(row)});$('#trend').replaceChildren();[2001,2010,2022].forEach(y=>{const d=document.createElement('div'),s=document.createElement('span'),v=document.createElement('strong');s.textContent=y;v.textContent=format(data.find(r=>r.Year===y&&r['Country Name']===country)?.[key]);d.append(s,v);$('#trend').append(d)});$('#table').replaceChildren();selected.forEach(r=>{const tr=document.createElement('tr');[r['Country Name'],r.Year,format(r[key])+' '+unit].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});$('#table').append(tr)});$('#status').textContent=label+' · '+year+' · '+valid.length+' countries with data'}
fetch('data.json').then(r=>{if(!r.ok)throw Error('Unable to load data');return r.json()}).then(d=>{data=d;[...new Set(data.map(r=>r['Country Name']))].sort().forEach(c=>$('#country').add(new Option(c,c)));$('#country').value='Jordan';update()}).catch(e=>{$('#status').textContent='Report data could not load. Please refresh to retry.';$('#export').disabled=true});
['year','metric','country'].forEach(id=>$('#'+id).addEventListener('change',()=>{if(data.length)update()}));$('#export').addEventListener('click',()=>{if(!selected.length)return;const key=metrics[$('#metric').value][0],csv=[['Country','Year',key],...selected.map(r=>[r['Country Name'],r.Year,r[key]??''])].map(row=>row.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='rama-development-data.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
